### ISSUE TITLE
Error on PRIVS: Functions/Procedures

### ISSUE THREAD

**Issue by gabrielpiassetta** [denishpatel/pg-clone-schema#37] opened 2021-03-05 14:31 UTC
I'm facing this error when trying to use the clone_schema function:

```
ERROR:  Action: PRIVS: Functions/Procedures  Diagnostics: line=PL/pgSQL function clone_schema(text,text,boolean,boolean) line 732 at EXECUTE. 42601. syntax error at or near "DEFAULT"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean) line 780 at RAISE
```

it comes from this generated query.

```
GRANT EXECUTE ON FUNCTION clone_schema_test_c.price_view_data (materialised_price_list_id integer, ofs integer, lim integer, filtering jsonb DEFAULT NULL::jsonb, sorting jsonb DEFAULT NULL::jsonb, flags jsonb DEFAULT NULL::jsonb) TO my_user;
```

which is generated by 
```
SELECT 'GRANT ' || rp.privilege_type || ' ON ' || r.routine_type || ' ' || quote_ident(dest_schema) || '.' || rp.routine_name || ' (' || pg_get_function_arguments(p.oid) || ') TO ' || string_agg(distinct rp.grantee, ',') || ';' as func_dcl
```

for some reason, `pg_get_function_arguments(p.oid)` is generating an invalid sql?

**Comment by MichaelDBA** [comment] 2021-03-05 14:35
well I think it's because the prototype header for the function definition itself includes DEFAULT keywords, but the function header for dropping or doing other actions on a function/procedure will barf if DEFAULT language is used.

**Comment by MichaelDBA** [comment] 2021-03-05 15:11
ha, finally an easy one!  There is another system func that returns the args WITHOUT DEFAULTS!  

This is now fixed.

**Closed by MichaelDBA** 2021-03-05 15:11 UTC

**Comment by gabrielpiassetta** [comment] 2021-03-05 15:52
Great! now everything is working! thank you very much @MichaelDBA

**Comment by MichaelDBA** [comment] 2021-03-05 17:03
Thank you, Gabriel, for helping to get these things cleaned up.  You 
always gave good info in your requests that made it easy to follow 
along.  Also, as I was fixing this stuff I added more SQL to the 
sampledb.sql file attached to this project for regression testing.

Gabriel Piassetta wrote on 3/5/2021 10:52 AM:
