### ISSUE TITLE
select clone_schema('sample', 'sample_clone', true, false);  NOT WORKING

### ISSUE THREAD

**Issue by jayjay8860** [denishpatel/pg-clone-schema#31] opened 2020-06-17 15:45 UTC
When I try to execute the subjected comment getting the below error.

SQL Error [P0001]: ERROR: Action: Tables  Diagnostics: line=SQL statement "INSERT INTO sample_clone.address SELECT * FROM sample.address;"
PL/pgSQL function clone_schema(text,text,boolean,boolean) line 346 at EXECUTE. 428C9. cannot insert into column "id"
  Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 753 at RAISE

**Comment by MichaelDBA** [comment] 2020-06-17 19:34
Can you provide DDL for sample.address table?

\d sample.address

**Comment by jayjay8860** [comment] 2020-06-18 04:39
It is available in sampledb.sql (In your package itself). However, I have tried with our development database and it looks fine except DDL generation commend. I don't see the DDL is getting generated in any of the tab/window. It's blank.

Really appreciate your development and help here.

**Comment by MichaelDBA** [comment] 2020-06-18 08:49
Ha, funny it's in our own sample database! There goes regression testing...

Problem is fixed in latest master branch.  The problem was that "generated always IDENTITY" columns would barf on the INSERT statement, unless OVERRIDING SYSTEM VALUE was specified.

Please open another issue with any other problems, like DDL generation.

**Closed by MichaelDBA** 2020-06-18 08:49 UTC
