### ISSUE TITLE
Fails when types are defined in public schema

### ISSUE THREAD

**Issue by Brent-Wood** [denishpatel/pg-clone-schema#82] opened 2022-09-12 02:04 UTC
Firstly, thanks for developing this, it seems to address an issue I'm having (almost :-)

I'm trying to use clone_schema() to create a complete working copy of an existing schema is a Postgres database with the extension Postgis installed. It fails with the message below:

*select clone_schema('trawl_dev', 'trawl_dev2', 'true', 'false');
NOTICE:  clone_schema version 1.8  July 15, 2022
NOTICE:  Linux: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:    11
ERROR:  Action: Tables  Diagnostics: line=PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 503 at EXECUTE. 42704. type "trawl_dev2.geometry" does not exist
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1709 at RAISE*

It seems to be assuming that any non-standard data type is defined inside the scheme being copied, but this is not the case as Postgis geometries are defined in the public schema but are available (and we use them) in any schema in the database:

fish=# \dT
*                                                      List of data types
 Schema |     Name      |                                             Description                                              
--------+---------------+------------------------------------------------------------------------------------------------------
 public | box2d         | postgis type: The type representing a 2-dimensional bounding box.
 public | box2df        | 
 public | box3d         | postgis type: The type representing a 3-dimensional bounding box.
 public | geography     | postgis type: The type representing spatial features with geodetic (ellipsoidal) coordinate systems.
 public | geometry      | postgis type: The type representing spatial features with planar coordinate systems.
 public | geometry_dump | postgis type: A composite type used to describe the parts of complex geometry.*

Is it possible to enhance the clone_schema() function to respect postgres datatypes already defined in the public schema (or any schema in the current search path)??

Essentially, if I am replicating a schema in a postgis database, I should not need to clone the types, as they are present by default.

Thanks

Brent Wood

**Comment by Brent-Wood** [comment] 2022-09-12 02:38
Ummm,

Looking at the function code (which really stretches my ability with SQL) I think the issue is that the public schema is removed from the search path when the clone_schema() function is run, therefore the Postgis types don't exist when the function tries to recreate the tables that have a column of geometry datatype in the scheme being copied. 

The obvious fix is to add the public schema to the search path when running the function, but I have a feeling this will break all sorts of things... 

Any suggestions?

Brent Wood

**Comment by MichaelDBA** [comment] 2022-09-12 14:24
Please provide some examples in your source schema that uses PostGIS.  Also, does the same problem occur when only cloning the schema not the data?  false, false are the last 2 parms when doing that.

**Comment by MichaelDBA** [comment] 2022-09-12 17:33
I was able to reproduce the problem with PostGIS and fixed it.  Check now with the latest code, please.

**Comment by Brent-Wood** [comment] 2022-09-12 20:39
Thanks for this - I will test it tomorrow when back at work. It is people like you that make Open Source software work and a vibrant community!!! Much appreciated.

**Comment by MichaelDBA** [comment] 2022-09-12 22:25
Thanks, but let's see if what i fixed is what you need fixed!

**Comment by Brent-Wood** [comment] 2022-09-14 04:27
It was the prompt response that is appreciated, if it worked that is even better!

It didn't work for me, but got further along I think, until a new error when setting the search path, looks like a comma where there shouldn't be, as below:

clone_test=# \dn
  List of schemas
  Name  |  Owner   
--------+----------
 public | postgres
 test1  | dba
(2 rows)

clone_test=# show search_path;
   search_path   
-----------------
 "$user", public
(1 row)

clone_test=# select clone_schema('test1','test2','true','false');
NOTICE:  clone_schema version 1.9  September 12, 2022
NOTICE:  Linux: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:     1
ERROR:  Action: Tables  Diagnostics: line=SQL statement "SELECT set_config('search_path', v_dummy, true)"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 508 at SQL statement. 22023. invalid value for parameter "search_path": ",public"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1715 at RAISE
clone_test=#

**Comment by MichaelDBA** [comment] 2022-09-14 13:14
hmmm, i cant see why the search_path is empty before "public" being appended to it.  Please grab the latest code that has some debug statements in it and run it again plz

**Comment by Brent-Wood** [comment] 2022-09-14 22:05
Thanks,

Hopefully this helps...

I create the new, clean db, install postgis, create schema/table with a script, I'll append this at the end...
then copy your sql & paste it to create the function in the database, then run :
select clone_schema('schema1','schema2','true','false');

Note there is no such schema "$user" in the database. I don't know if that matters, but we don't have personal/role based schemas.

schema_test=# show search_path;
   search_path   
-----------------
 "$user", public
(1 row)

schema_test=# select clone_schema('schema1','schema2','true','false');


NOTICE:  clone_schema version 1.9  September 12, 2022
NOTICE:  Linux: PostgreSQL 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:     1
INFO:  DEBUG: v_dummy1=
INFO:  DEBUG: v_dummy2=
INFO:  DEBUG: v_dummy3=,public
ERROR:  Action: Tables  Diagnostics: line=SQL statement "SELECT set_config('search_path', v_dummy, true)"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 512 at SQL statement. 22023. invalid value for parameter "search_path": ",public"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1719 at RAISE


I then tried setting my initial search_path to just "public", but this made no difference:

schema_test=# set search_path='public';
SET
schema_test=# show search_path;
 search_path 
-------------
 public
(1 row)

schema_test=# select clone_schema('schema1','schema2','true','false');
NOTICE:  clone_schema version 1.9  September 12, 2022
NOTICE:  Linux: PostgreSQL 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:     1
INFO:  DEBUG: v_dummy1=
INFO:  DEBUG: v_dummy2=
INFO:  DEBUG: v_dummy3=,public
ERROR:  Action: Tables  Diagnostics: line=SQL statement "SELECT set_config('search_path', v_dummy, true)"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 512 at SQL statement. 22023. invalid value for parameter "search_path": ",public"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1719 at RAISE



The script I run to create the db & objects to test the clone_schema() function:

#! /bin/bash
#
DB=schema_test

dropdb $DB
createdb $DB

psql -d $DB -c "create extension postgis;"
psql -d $DB -c "create schema schema1;"
psql -d $DB -c "create table schema1.table1
                 (id   serial primary key,
                  name text,
                  geom geometry (POINT,4326));"
psql -d $DB -c "insert into schema1.table1 (name, geom)
                         values ('text', ST_SetSRID(ST_MakePoint(175, -45),4326));

# create clone_schema function
# run select clone_schema('schema1','schema2','true','false');

**Comment by Brent-Wood** [comment] 2022-09-14 22:06
Sigh - I had '#" for comments in my test, which has been interpreted as bold...

**Comment by MichaelDBA** [comment] 2022-09-15 11:06
let's try it again, added more debug statements to capture all search_path progressions, so get the latest code and run again plz.

**Comment by Brent-Wood** [comment] 2022-09-15 21:07
Done...

select clone_schema('schema1','schema2','true','false','true');
NOTICE:  clone_schema version 1.9  September 15, 2022
NOTICE:  Linux: PostgreSQL 12.12 (Ubuntu 12.12-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
INFO:  DEBUG1a: search_path="$user", public
INFO:  DEBUG1b: src_path_old="$user", public
INFO:  DEBUG2: new search_path=schema1
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:     1
INFO:  DEBUG3: setting search_path to empty string...
INFO:  DEBUG4: search_path=
INFO:  DEBUG5: search_path=
INFO:  DEBUG6: search_path=,public
ERROR:  Action: Tables  Diagnostics: line=SQL statement "SELECT set_config('search_path', v_dummy, true)"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 518 at SQL statement. 22023. invalid value for parameter "search_path": ",public"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1723 at RAISE


I still get the same error with the search path set to just the public schema...

schema_test=# show search_path;
 search_path 
-------------
 public
(1 row)

schema_test=# select clone_schema('schema1','schema2','true','false','true');
NOTICE:  clone_schema version 1.9  September 15, 2022
NOTICE:  Linux: PostgreSQL 12.12 (Ubuntu 12.12-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
INFO:  DEBUG1a: search_path=public
INFO:  DEBUG1b: src_path_old=public
INFO:  DEBUG2: new search_path=schema1
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:     1
INFO:  DEBUG3: setting search_path to empty string...
INFO:  DEBUG4: search_path=
INFO:  DEBUG5: search_path=
INFO:  DEBUG6: search_path=,public
ERROR:  Action: Tables  Diagnostics: line=SQL statement "SELECT set_config('search_path', v_dummy, true)"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 518 at SQL statement. 22023. invalid value for parameter "search_path": ",public"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1723 at RAISE

**Comment by MichaelDBA** [comment] 2022-09-15 22:05
ONE LAST TIME, please run again with the latest code.  Thanks for your patience.

**Comment by Brent-Wood** [comment] 2022-09-15 22:11
No problem, thank you for your efforts to resolve this!!

select clone_schema('schema1','schema2','true','false','true');

NOTICE:  clone_schema version 1.9  September 15, 2022
NOTICE:  Linux: PostgreSQL 12.12 (Ubuntu 12.12-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
INFO:  DEBUG1a: search_path=public
INFO:  DEBUG1b: src_path_old=public
INFO:  DEBUG02: new search_path=schema1
INFO:  DEBUG03: search_path=schema1
NOTICE:    COLLATIONS cloned:     0
INFO:  DEBUG04: search_path=schema1
NOTICE:       DOMAINS cloned:     0
INFO:  DEBUG05: search_path=schema1
NOTICE:         TYPES cloned:     2
INFO:  DEBUG06: search_path=schema1
NOTICE:     SEQUENCES cloned:     1
INFO:  DEBUG07: search_path=schema1
INFO:  DEBUG08: setting search_path to empty string...
INFO:  DEBUG11: search_path=
INFO:  DEBUG12: search_path=
INFO:  DEBUG13: search_path=,public
ERROR:  Action: Tables  Diagnostics: line=SQL statement "SELECT set_config('search_path', v_dummy, true)"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 533 at SQL statement. 22023. invalid value for parameter "search_path": ",public"
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1745 at RAISE
schema_test=#

**Comment by MichaelDBA** [comment] 2022-09-16 10:31
OK, give it another shot with the latest code.

**Comment by Brent-Wood** [comment] 2022-09-17 22:56
Seems OK with my test at home...  will try Monday at work with a real test case... Thanks for your efforts to sort this out!!

              select clone_schema('schema1','schema2','true','false');-45),4326)NOTICE:  clone_schema version 1.9  September 16, 2022
NOTICE:  Linux: PostgreSQL 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, 64-bit
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:     1
NOTICE:        TABLES cloned:     1
NOTICE:      SEQUENCES set:       1
NOTICE:     IDENTITIES set:       0
NOTICE:         VIEWS cloned:     0
NOTICE:     MAT VIEWS cloned:     0
NOTICE:     FUNCTIONS cloned:     0
NOTICE:      TRIGGERS cloned:     0
NOTICE:      RULES    cloned:     0
NOTICE:      POLICIES cloned:     0
NOTICE:   COMMENTS(1) cloned:     0
NOTICE:   COMMENTS(2) cloned:     0
NOTICE:    DFLT PRIVS cloned:     0
NOTICE:  SCHEMA PRIVS cloned:     2
NOTICE:    SEQ. PRIVS cloned:     2
NOTICE:    FUNC PRIVS cloned:     0
NOTICE:   TABLE PRIVS cloned:     7
NOTICE:        TABLES copied:     1
NOTICE:         FKEYS cloned:     0
 clone_schema 
--------------

**Comment by Brent-Wood** [comment] 2022-09-18 19:57
Hmmm... I think it works, but our db design is broken I think... we have indexes on tables in other schemas created without specifying a schema, so they are in the public schema. Therefore the clone_schema() function tries to create a duplicate index & exits - which is what it should do!!!

I will suggest we look at our design & tidy it up!

Thanks for this, appreciated!!

**Comment by MichaelDBA** [comment] 2022-09-18 22:40
Per README under the limitations section:
"You should not clone the "public" schema. The resulting output may not be accurate even if it finishes without any errors."

**Comment by Brent-Wood** [comment] 2022-09-19 00:07
I read that, I'm not cloning the public schema, & am trying to sort out why I now get a new error:. The target schema does not exist, the index exists in the source schema as normal, but running this seems to tell me otherwise

select clone_schema('trawl_dev','trawl_dev2','true','false','true');
NOTICE:  clone_schema version 1.9  September 16, 2022
NOTICE:  Linux: PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
INFO:  DEBUG: search_path="$user", public
INFO:  DEBUG: src_path_old="$user", public
INFO:  DEBUG: new search_path=trawl_dev
NOTICE:    COLLATIONS cloned:     0
NOTICE:       DOMAINS cloned:     0
NOTICE:         TYPES cloned:     2
NOTICE:     SEQUENCES cloned:    11
INFO:  DEBUG: search_path=trawl_dev
INFO:  DEBUG: setting search_path to empty string:
ERROR:  Action: Tables  Diagnostics: line=SQL statement "CREATE TABLE trawl_dev2.t_site (
  site_key integer NOT NULL,
  initial_trip character varying(7) NOT NULL,
  stn_code character varying(6) NULL,
  area character varying(4) NULL,
  stratum character varying(4) NULL,
  lat integer NULL,
  nors character varying(1) NULL,
  long integer NULL,
  eorw character varying(1) NULL,
  site_type character varying(8) NULL,
  dlat numeric(7,5) NULL,
  dlon numeric(8,5) NULL,
  position geometry NULL,
  CONSTRAINT pk_t_site PRIMARY KEY (site_key),
  CONSTRAINT ui_t_site UNIQUE (initial_trip, stn_code),
  CONSTRAINT enforce_dims_geom CHECK ((st_ndims("position") = 2)),
  CONSTRAINT enforce_geotype_geom CHECK (((geometrytype("position") = 'POINT'::text) OR ("position" IS NULL))),
  CONSTRAINT enforce_srid_geom CHECK ((st_srid("position") = 4326))
) TABLESPACE pg_default;
CREATE UNIQUE INDEX ui_t_site ON trawl_dev2.t_site USING btree (initial_trip, stn_code);
"
PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 512 at EXECUTE. 42P07. relation "ui_t_site" already exists
CONTEXT:  PL/pgSQL function clone_schema(text,text,boolean,boolean,boolean) line 1718 at RAISE

**Comment by Brent-Wood** [comment] 2022-09-19 03:12
Do you want this filed as a new issue, as you do seem to resolved the original one?

**Comment by MichaelDBA** [comment] 2022-09-21 11:38
I'm closing this since it fixed your problem.

**Closed by MichaelDBA** 2022-09-21 11:38 UTC
